apiVersion: v1
appVersion: "0.1.99.2"
description: NSR (National Stoppalce Register)
name: sobek
version: 0.1.0
keywords:
- sobek
sources:
- https://github.com/entur/sobek
maintainers:
- name: 'team-ror'
  email: team.rutedata@entur.org
engine: gotpl
