replicas: 2

deployment:
  name: sobek

rollingUpdate:
  maxSurge: 1
  maxUnavailable: 1

resources:
  memLimit: 10000Mi
  cpuRequest: 1200m
  memRequest: 7500Mi
  xss: 1024m
  xmx: 7g

configMapMount:
   name: sobek-config

image:
  identifier: <+artifacts.primary.image>
  imagePullPolicy: Always

service:
  http:
    externalPort: 80
    internalPort: 8777
  jolokia:
    internalPort: 8778
rbac:
  enabled: false
ingress:
  name: vehicle-register-v1


secrets:
  sobek-psql-credentials:
    - SPRING_DATASOURCE_PASSWORD